# compose.yaml
name: bb
services:
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    post_start:
      - command: sh -c "sleep 5 && influxdb3 create token --admin --format json > /etc/influxdb3/config/token.json"
        user: root

    volumes:
      - type: bind
        source: ./data/influxdb3/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: ./data/influxdb3/plugins
        target: /var/lib/influxdb3/plugins
      - type: bind
        source: ./config/influxdb
        target: /etc/influxdb3/config

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto:/mosquitto/config
